# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('p480', models.CharField(max_length=120)),
                ('p720', models.CharField(max_length=120)),
                ('p1080', models.CharField(max_length=120)),
                ('sub_file', models.CharField(max_length=120)),
                ('AnimeTitle', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='index.AnimeTitle')),
            ],
        ),
    ]
