# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodes',
            name='AnimeTitle',
            field=models.ForeignKey(default=models.CharField(max_length=120), on_delete=django.db.models.deletion.CASCADE, to='index.AnimeTitle'),
        ),
    ]
