# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20160628_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('p480', models.CharField(max_length=120)),
                ('p720', models.CharField(max_length=120)),
                ('p1080', models.CharField(max_length=120)),
                ('sub_file', models.CharField(max_length=120)),
                ('AnimeTitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.AnimeTitle')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='episodes',
            name='AnimeTitle',
        ),
        migrations.DeleteModel(
            name='Episodes',
        ),
    ]
