# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20160703_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('AnimeTitles', models.ManyToManyField(to='index.AnimeTitle')),
            ],
        ),
    ]
