# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animetitle',
            options={'ordering': ['release_time']},
        ),
        migrations.AddField(
            model_name='animetitle',
            name='release_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
