# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20160703_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animetitle',
            name='release_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
