# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20160703_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='animetitle',
            name='img',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
